### ISSUE TITLE
重复下载

### ISSUE THREAD

**Issue by mengke-mk** [tianxianbaobao/UCS#1]
每次同步都会把以前下过的课件重复下一边，这样很浪费ipv4的流量啊。

**Comment by mengke-mk** [comment]
但是万一老师更新了我也不知道md5值啊，有什么好办法吗。

**Comment by mengke-mk** [comment]
目前按名称处理，同名跳过

**Comment by freemandealer** [comment]
增加 --force-update功能参数，可以强制重复下载，用于更新已存在的文件
